//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DAL.SQLQueries", typeof(SQLQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM 
        ///    [Favorites]
        ///WHERE 
        ///    [FavoriteID]= @FavoriteID;.
        /// </summary>
        internal static string DeleteFavorite {
            get {
                return ResourceManager.GetString("DeleteFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM 
        ///    [OngoingOrder]
        ///WHERE 
        ///    [ServiceID] = @ServiceID;.
        /// </summary>
        internal static string DeleteOngoingOrder {
            get {
                return ResourceManager.GetString("DeleteOngoingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [Ratings]  
        ///WHERE [ServiceID] = @ServiceID AND [ClientID] = @ClientID;.
        /// </summary>
        internal static string DeleteRating {
            get {
                return ResourceManager.GetString("DeleteRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM 
        ///    [Services]
        ///WHERE 
        ///    [ServiceID] = @ServiceID;.
        /// </summary>
        internal static string DeleteService {
            get {
                return ResourceManager.GetString("DeleteService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [Users] WHERE [UserId] = @UserId;.
        /// </summary>
        internal static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    [ServiceID], 
        ///    [ProviderID], 
        ///    [ServiceName], 
        ///    [CategoryID], 
        ///    [Price], 
        ///    [Description], 
        ///    [ContactPhone], 
        ///    [CreatedOn], 
        ///    [Images]
        ///FROM 
        ///    [Services];.
        /// </summary>
        internal static string GetAllServices {
            get {
                return ResourceManager.GetString("GetAllServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///    CASE
        ///        WHEN [SenderID] = @UserId THEN [ReceiverID]
        ///        ELSE [SenderID]
        ///    END AS ContactUserID,
        ///    MAX([SentOn]) AS LastSentOn
        ///FROM [Messages]
        ///WHERE [SenderID] = @UserId OR [ReceiverID] = @UserId
        ///GROUP BY 
        ///    CASE
        ///        WHEN [SenderID] = @UserId THEN [ReceiverID]
        ///        ELSE [SenderID]
        ///    END
        ///ORDER BY LastSentOn DESC;.
        /// </summary>
        internal static string GetMessagedPeople {
            get {
                return ResourceManager.GetString("GetMessagedPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    [ServiceID], 
        ///    [ProviderID], 
        ///    [ServiceName], 
        ///    [CategoryID], 
        ///    [Price], 
        ///    [Description], 
        ///    [ContactPhone], 
        ///    [CreatedOn], 
        ///    [Images]
        ///FROM 
        ///    [Services]
        ///WHERE 
        ///    [CategoryID] = @CategoryID;.
        /// </summary>
        internal static string GetServiceByCategoryID {
            get {
                return ResourceManager.GetString("GetServiceByCategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    [ServiceID], 
        ///    [ProviderID], 
        ///    [ServiceName], 
        ///    [CategoryID], 
        ///    [Price], 
        ///    [Description], 
        ///    [ContactPhone], 
        ///    [CreatedOn], 
        ///    [Images]
        ///FROM 
        ///    [Services]
        ///WHERE 
        ///    [ProviderID] = @ProviderID;.
        /// </summary>
        internal static string GetServiceByProviderID {
            get {
                return ResourceManager.GetString("GetServiceByProviderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    [ServiceID], 
        ///    [ProviderID], 
        ///    [ServiceName], 
        ///    [CategoryID], 
        ///    [Price], 
        ///    [Description], 
        ///    [ContactPhone], 
        ///    [CreatedOn], 
        ///    [Images],
        ///[Location]
        ///FROM 
        ///    [Services]
        ///WHERE 
        ///    [ServiceID] = @ServiceID;.
        /// </summary>
        internal static string GetServiceByServiceID {
            get {
                return ResourceManager.GetString("GetServiceByServiceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    [ServiceID],
        ///    [ProviderID],
        ///    [ServiceName],
        ///    [CategoryID],
        ///    [Price],
        ///    [Description],
        ///    [ContactPhone],
        ///    [CreatedOn],
        ///    [Images]
        ///FROM 
        ///    [Services]
        ///WHERE 
        ///    [ServiceName] LIKE &apos;%&apos; + @ServiceName + &apos;%&apos;;.
        /// </summary>
        internal static string GetServiceByServiceName {
            get {
                return ResourceManager.GetString("GetServiceByServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [UserId], [ProfilePicture] WHERE [UsereId] = @UserId AND [ProfilePicture] = @ProfilePicture.
        /// </summary>
        internal static string GetUserPPName {
            get {
                return ResourceManager.GetString("GetUserPPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [Categories] ([CategoryID], [CategoryName]) VALUES (NEWID(), @CategoryName);.
        /// </summary>
        internal static string InsertCategory {
            get {
                return ResourceManager.GetString("InsertCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [Favorites] ([FavoriteID], [ServiceID], [UserId]) VALUES (NEWID(), @ServiceID, @UserId);.
        /// </summary>
        internal static string InsertFavorite {
            get {
                return ResourceManager.GetString("InsertFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [Messages] 
        ///([MessageID], [SenderID], [ReceiverID], [MessageContent], [SentOn], [MessageStatus]) 
        ///VALUES 
        ///(NEWID(), @SenderID, @ReceiverID, @MessageContent, @SentOn, @MessageStatus);.
        /// </summary>
        internal static string InsertMessage {
            get {
                return ResourceManager.GetString("InsertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [OngoingOrder] 
        ///([OrderID], [ServiceID], [ProviderID], [ServiceName], [CategoryID], [Price], [UserID], [OrderDate], [Status]) 
        ///VALUES 
        ///(NEWID(), @ServiceID, @ProviderID, @ServiceName, @CategoryID, @Price, @UserID, @OrderDate, @Status);.
        /// </summary>
        internal static string InsertOngoingOrder {
            get {
                return ResourceManager.GetString("InsertOngoingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [Ratings] ([RatingID],[ServiceID], [ClientID], [Rating], [Comment], [CreatedOn])
        ///VALUES (@RatingID,@ServiceID, @ClientID, @Rating, @Comment, @CreatedOn);.
        /// </summary>
        internal static string InsertRating {
            get {
                return ResourceManager.GetString("InsertRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [Services] 
        ///(
        ///    [ServiceID], 
        ///    [ProviderID], 
        ///    [ServiceName], 
        ///    [CategoryID], 
        ///    [Price], 
        ///    [Description], 
        ///    [ContactPhone], 
        ///    [CreatedOn], 
        ///    [Images],
        ///[Location]
        ///) 
        ///VALUES 
        ///(
        ///    NEWID(), 
        ///    @ProviderID, 
        ///    @ServiceName, 
        ///    @CategoryID, 
        ///    @Price, 
        ///    @Description, 
        ///    @ContactPhone, 
        ///    @CreatedOn, 
        ///    @Images,
        ///@Location
        ///);.
        /// </summary>
        internal static string InsertService {
            get {
                return ResourceManager.GetString("InsertService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [Users] ([UserId], [Username], [Email], [Password], [UserType], [CreatedOn], [PhoneNumber]) VALUES (NEWID(), @Username, @Email, @Password,@UserType, @CreatedOn, @PhoneNumber);.
        /// </summary>
        internal static string InsertUser {
            get {
                return ResourceManager.GetString("InsertUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * 
        ///FROM [ServiceRatings];.
        /// </summary>
        internal static string SelectAllRatings {
            get {
                return ResourceManager.GetString("SelectAllRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  [CategoryID], [CategoryName]  FROM [Categories];.
        /// </summary>
        internal static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [CategoryID], [CategoryName] FROM [Categories] WHERE [CategoryID] = @CategoryID.
        /// </summary>
        internal static string SelectCategoryById {
            get {
                return ResourceManager.GetString("SelectCategoryById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM [Favorites] WHERE [UserId] = @UserId.
        /// </summary>
        internal static string SelectFavoriteByUserId {
            get {
                return ResourceManager.GetString("SelectFavoriteByUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///FROM [Ratings]
        ///WHERE [ServiceID] IN (
        ///    SELECT [ServiceID]
        ///    FROM [Ratings]
        ///    GROUP BY [ServiceID]
        ///    HAVING AVG([Rating]) &gt; 4
        ///);.
        /// </summary>
        internal static string SelectHighestRated {
            get {
                return ResourceManager.GetString("SelectHighestRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * 
        ///FROM [Messages] 
        ///WHERE 
        ///    ([SenderID] = @SenderID AND [ReceiverID] = @ReceiverID) 
        ///    OR ([SenderID] = @ReceiverID AND [ReceiverID] = @SenderID)
        ///ORDER BY [SentOn];.
        /// </summary>
        internal static string SelectMessages {
            get {
                return ResourceManager.GetString("SelectMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 3
        ///       [MessageID],
        ///       [SenderID],
        ///       [ReceiverID],
        ///       [MessageContent],
        ///       [SentOn],
        ///       [MessageStatus]
        ///FROM  [Messages]
        ///WHERE [ReceiverID] = @ReceiverID
        ///ORDER BY [SentOn] DESC;.
        /// </summary>
        internal static string SelectMessagesByRecieverID {
            get {
                return ResourceManager.GetString("SelectMessagesByRecieverID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT ReceiverID AS ContactUserID
        ///FROM Messages
        ///WHERE SenderID = @UserID
        ///
        ///UNION
        ///
        ///SELECT DISTINCT SenderID AS ContactUserID
        ///FROM Messages
        ///WHERE ReceiverID = @UserID.
        /// </summary>
        internal static string SelectMessagesBySenderAndReciever {
            get {
                return ResourceManager.GetString("SelectMessagesBySenderAndReciever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [OrderID], [ServiceID], [ProviderID], [ServiceName], [CategoryID], [Price], [UserID], [OrderDate], [Status]
        ///FROM [OngoingOrder] 
        ///WHERE [ProviderID] = @ProviderID;.
        /// </summary>
        internal static string SelectOngoingOrderByProviderID {
            get {
                return ResourceManager.GetString("SelectOngoingOrderByProviderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [OrderID], [ServiceID], [ProviderID], [ServiceName], [CategoryID], [Price], [UserID], [OrderDate], [Status]
        ///FROM [OngoingOrder] 
        ///WHERE [UserID] = @UserID;.
        /// </summary>
        internal static string SelectOngoingOrderByUserID {
            get {
                return ResourceManager.GetString("SelectOngoingOrderByUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * 
        ///FROM [Ratings];.
        /// </summary>
        internal static string SelectRatings {
            get {
                return ResourceManager.GetString("SelectRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * 
        ///FROM [Ratings]
        ///WHERE [ClientID] = @ClientID;.
        /// </summary>
        internal static string SelectRatingsByClientID {
            get {
                return ResourceManager.GetString("SelectRatingsByClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * 
        ///FROM [Ratings]  
        ///WHERE [ServiceID] = @ServiceID;.
        /// </summary>
        internal static string SelectRatingsByServiceID {
            get {
                return ResourceManager.GetString("SelectRatingsByServiceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * 
        ///FROM [Ratings]  
        ///WHERE [ServiceID] = @ServiceID AND [ClientID] = @ClientID;.
        /// </summary>
        internal static string SelectRatingsByServiceIDAndClientID {
            get {
                return ResourceManager.GetString("SelectRatingsByServiceIDAndClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [UserId], [Username], [Email], [CreatedOn], [ProfilePicture], [PhoneNumber]  FROM [Users] WHERE [UserId] = @UserId.
        /// </summary>
        internal static string SelectUserById {
            get {
                return ResourceManager.GetString("SelectUserById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [UserId], [Username],[Password], [Email], [UserType], [CreatedOn], [ProfilePicture], [PhoneNumber] FROM [Users] WHERE [Username] = @Username ;.
        /// </summary>
        internal static string SelectUserByNameAndPassword {
            get {
                return ResourceManager.GetString("SelectUserByNameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [UserId], [Username] FROM [Users] WHERE [Username] = @Username ;.
        /// </summary>
        internal static string SelectUserByUsername {
            get {
                return ResourceManager.GetString("SelectUserByUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [UserId], [Username], [Email], [CreatedOn], [PhoneNumber], [ProfilePicture] FROM [Users];.
        /// </summary>
        internal static string SelectUsers {
            get {
                return ResourceManager.GetString("SelectUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [OngoingOrder] 
        ///SET [Status] = @Status
        ///WHERE [OrderID] = @OrderID;.
        /// </summary>
        internal static string UpdateOngoingOrderStatus {
            get {
                return ResourceManager.GetString("UpdateOngoingOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [Ratings] 
        ///SET [Rating] = @Rating,
        ///    [Comment] = @Comment
        ///WHERE [ServiceID] = @ServiceID AND [ClientID] = @ClientID;.
        /// </summary>
        internal static string UpdateRating {
            get {
                return ResourceManager.GetString("UpdateRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE 
        ///    [Services]
        ///SET 
        ///    [ServiceName] = @ServiceName, 
        ///    [CategoryID] = @CategoryID, 
        ///    [Price] = @Price, 
        ///    [Description] = @Description, 
        ///    [ContactPhone] = @ContactPhone, 
        ///    [Images] = @Images
        ///WHERE 
        ///    [ServiceID] = @ServiceID;.
        /// </summary>
        internal static string UpdateService {
            get {
                return ResourceManager.GetString("UpdateService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [Users] SET [Username] = @Username, [Email] = @Email, [Password] = @Password, [PhoneNumber] = @PhoneNumber WHERE [UserId] = @UserId;.
        /// </summary>
        internal static string UpdateUser {
            get {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [Users] SET [ProfilePicture] = @ProfilePicture WHERE [UserId] = @UserId;.
        /// </summary>
        internal static string UpdateUserPPName {
            get {
                return ResourceManager.GetString("UpdateUserPPName", resourceCulture);
            }
        }
    }
}
